version: "3"

networks:
  proxy_my-network:
    external: true

volumes:
  rec_dir-site:
    external: true
    
services:
# CONTAINER 
  apache-container:
    image: httpd:2.4
    container_name: sel-apache-container
    environment:
      VIRTUAL_HOST: biscuretuannt.tk
    networks:
      - proxy_my-network
    volumes:
      - rec_dir-site:/home/sites
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    expose:
      - "80"