version: "3"

networks:
  mycode_my-network:
    external: true
    
services:
# CONTAINER 
  container1:
    image: httpd:2.4
    container_name: container-1
    environment:
      VIRTUAL_HOST: t-d-247.tk
    networks:
      - mycode_my-network
    expose:
      - "80"