version: "3"

# NETWORK
networks:
  proxy_my-network:
    external: true
      
services:
# CONTAINER MYSQL
  my-mysql:
    container_name: mysql-container
    image: "mysql:5.7.23"
    hostname: mysql
    restart: always
    networks:
      - proxy_my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=social
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password 